### ISSUE TITLE
<vaadin-split-layout> produces an error when it has only one (visible) child

### ISSUE THREAD

**Issue by amitmerin** [vaadin/vaadin-split-layout#123] opened 2018-10-11 18:06 UTC
When a `<vaadin-split-layout>` has only one child or if all of its children except one are `display:none;` the splitter is still displayed on the screen and produces errors when clicked on.
I would expect that the component would handle these situations by identifying it has one visible child and not displaying the splitter.

**Comment by limonte** [comment] 2018-10-15 08:19
Hello @amitmerin and thank you for reporing this!

Here's the live demo of the use-case you described: https://crystal-sweater.glitch.me/ 
Here's the source code: https://glitch.com/edit/#!/crystal-sweater

> if all of its children except one are display:none; the splitter is still displayed on the screen
That's correct.

> and produces errors when clicked on.
I can't reproduce this. Which browser and what version of `vaadin-split-layout` are you using?

**Comment by amitmerin** [comment] 2018-10-15 13:14
1. If the splitter has only one child - which could happen in a case of conditional rendering, you will gen an error `Uncaught TypeError: Cannot read property 'style' of undefined`.
That's easy to reproduce - just remove the second iframe.
2. The second type of error was more difficult to reproduce, I need to work on it. 
I have a `lit-element` based project and I get the error when all of its children except one are `display:none;`. 
The error `unable to preventDefault inside passive event listener invocation.` comes from `@polymer/polymer/lib/utils/gestures.js`.

**Comment by web-padawan** [comment] 2019-06-14 11:08
The error number 1. from the above comment should be fixed. We could dispatch warning instead.

**Closed** 2019-06-25 12:07 UTC
Labels: bug
