### ISSUE TITLE
Splitter position should be fixed after initial render

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-split-layout#41] opened 2017-01-03 09:09 UTC
It is a bit unexpected that the splitter keeps moving back and forth in the following example

```html
<!doctype html>
<head>

<script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>
<link rel="import" href="bower_components/vaadin-split-layout/vaadin-split-layout.html">

<body>

<vaadin-split-layout id="split">
<div></div>
<div id="s">Second</div>
</vaadin-split-layout>
<script>
setInterval(function() {
  if (s.style.width != "500px") {
    s.style.width="500px";
  } else  {
    s.style.width="200px";
  }
},500);

</script>
```

**Comment by platosha** [comment] 2017-01-03 09:17
This will block any width from being applied after the split layout init. Why?

**Comment by web-padawan** [comment] 2020-03-27 17:37
Closing this as working as intended, according to the above comment.

**Closed by web-padawan** 2020-03-27 17:37 UTC
